const TEXTS = {
  KRONOMETER_TITLE: 'KRONOMETER',
  KRONOMETER_DEFINITION: 'This is basic kronometer for right now!',
  KRONOMETER_FINISH: 'FINISH'
};

const INPUT_TEXTS = {
  KRONOMETER_INPUT_PLACEHOLDER: 'Please type second for kronometer...',
};

const BUTTON_TEXT = {
  KRONOMETER_BUTTON_START_TEXT: 'START',
  KRONOMETER_BUTTON_STOP_TEXT: 'STOP'
};

export {
  TEXTS,
  INPUT_TEXTS,
  BUTTON_TEXT
};